version: '3'

services:
  backend:
    image: ghcr.io/..../back
    restart: always
    labels:
        - traefik.enable=true
        - traefik.http.routers.back-dev.rule=Host(`MY-DOMAIN.COM`) && PathPrefix(`/api/v1`)
        - traefik.http.routers.back-dev.tls=true
        - traefik.http.routers.back-dev.tls.certresolver=le
        - traefik.http.services.back-dev.loadbalancer.server.port=4000
        - traefik.http.middlewares.back-dev.buffering.memRequestBodyBytes=11000000

    volumes:
        - ./.env:/usr/src/app/.env
    command: >
      sh -c "npm run db:build:migrations && npm run db:migrate && npm start"
    networks:
        - traefik-net
        - traefik-internal

  database:
    image: 'postgres'
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
        - ./storage/postgres/:/var/lib/postgresql/data/
    networks:
        - traefik-internal

networks:
  traefik-net:
    external: true
  traefik-internal:
    external: false
